### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amanda-tan**
Added Pangeo to the Open Source Software Engineering list of Awesomeness

### CODE REVIEW

**Comment by vsoch** [comment]
Great! A few quick comments for discussion:

 - I think it would be more appropriate to add a category for Geoscience, and the organization would better fit there. Scalable computing is pretty general, and the interested viewer is probably going to want to browse based on learning about a domain. If noting that scalable computing is super important, you could add that to the description after the link.
 - Whatever section we add, let's make sure that both the navigation links and following sections are in alphabetical order!

**Comment by amanda-tan** [comment]
Sounds perfectly fine to me. Should I just close this pull request and you insert the link into the appropriate section? Thanks.

**Comment by vsoch** [comment]
Oh, I'd like to give you credit for the commit! If it's okay with you, I'll update your branch with the fixes. I might not get to it until tomorrow though, sort of focused on something else and it's almost dinnertime :)

**Review by vsoch — APPROVED** [review]
Looks good, thanks for your contribution @amanda-tan !

**Pull request merged**
